from enum import StrEnum


class CampaignStatus(StrEnum):
    DRAFT = "DRAFT"
    RANKING = "RANKING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class CampaignJobStatus(StrEnum):
    WAITING_APPROVAL = "WAITING_APPROVAL"
    APPROVED = "APPROVED"
    QUEUED = "QUEUED"
    EXECUTING = "EXECUTING"
    PAUSED = "PAUSED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    SUBMITTED = "SUBMITTED"
    FAILED = "FAILED"


class ApplicationStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    ANALYZED = "ANALYZED"
    QUALIFIED = "QUALIFIED"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    APPROVED = "APPROVED"
    QUEUED = "QUEUED"
    EXECUTING = "EXECUTING"
    SUBMITTED = "SUBMITTED"
    PAUSED = "PAUSED"
    CANCELLED = "CANCELLED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    PLATFORM_LIMIT = "PLATFORM_LIMIT"
    DOM_CHANGED = "DOM_CHANGED"
    FAILED = "FAILED"


class AgentRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"


class AgentStepStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AgentEventType(StrEnum):
    RUN_CREATED = "AGENT_RUN_CREATED"
    RUN_STARTED = "AGENT_RUN_STARTED"
    STEP_STARTED = "AGENT_STEP_STARTED"
    STEP_FINISHED = "AGENT_STEP_FINISHED"
    STEP_FAILED = "AGENT_STEP_FAILED"
    USER_ACTION_REQUIRED = "USER_ACTION_REQUIRED"
    RUN_PAUSED = "AGENT_RUN_PAUSED"
    RUN_RESUMED = "AGENT_RUN_RESUMED"
    RUN_COMPLETED = "AGENT_RUN_COMPLETED"
    RUN_CANCELLED = "AGENT_RUN_CANCELLED"
    RUN_FAILED = "AGENT_FAILED"
    RUN_TIMED_OUT = "AGENT_TIMED_OUT"
