from enum import StrEnum


class CampaignStatus(StrEnum):
    DRAFT = "DRAFT"
    RANKING = "RANKING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class CampaignJobStatus(StrEnum):
    WAITING_APPROVAL = "WAITING_APPROVAL"
    APPROVED = "APPROVED"
    QUEUED = "QUEUED"
    EXECUTING = "EXECUTING"
    PAUSED = "PAUSED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    SUBMITTED = "SUBMITTED"
    MANUAL_REQUIRED = "MANUAL_REQUIRED"
    FAILED = "FAILED"


class ApplicationStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    ANALYZED = "ANALYZED"
    QUALIFIED = "QUALIFIED"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    APPROVED = "APPROVED"
    QUEUED = "QUEUED"
    EXECUTING = "EXECUTING"
    SUBMITTED = "SUBMITTED"
    MANUAL_REQUIRED = "MANUAL_REQUIRED"
    PAUSED = "PAUSED"
    CANCELLED = "CANCELLED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    PLATFORM_LIMIT = "PLATFORM_LIMIT"
    DOM_CHANGED = "DOM_CHANGED"
    RISK_CONTROL = "RISK_CONTROL"
    UNKNOWN_STATE = "UNKNOWN_STATE"
    FAILED = "FAILED"


class AgentRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"


class AgentStepStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class BrowserTaskStatus(StrEnum):
    PENDING = "PENDING"
    CONNECTING = "CONNECTING"
    RUNNING = "RUNNING"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class BrowserActionType(StrEnum):
    NAVIGATE = "NAVIGATE"
    CLICK = "CLICK"
    TYPE = "TYPE"
    EXTRACT = "EXTRACT"
    SCROLL = "SCROLL"
    WAIT = "WAIT"
    CHECK_STATE = "CHECK_STATE"
    SCREENSHOT = "SCREENSHOT"
    REQUEST_USER_ACTION = "REQUEST_USER_ACTION"


class BrowserTaskEventType(StrEnum):
    TASK_CREATED = "BROWSER_TASK_CREATED"
    EXTENSION_CONNECTED = "EXTENSION_CONNECTED"
    ACTION_SENT = "BROWSER_ACTION_SENT"
    ACTION_RESULT = "BROWSER_ACTION_RESULT"
    USER_ACTION_REQUIRED = "BROWSER_USER_ACTION_REQUIRED"
    TASK_COMPLETED = "BROWSER_TASK_COMPLETED"
    TASK_CANCELLED = "BROWSER_TASK_CANCELLED"
    TASK_FAILED = "BROWSER_TASK_FAILED"


class AgentEventType(StrEnum):
    RUN_CREATED = "AGENT_RUN_CREATED"
    RUN_STARTED = "AGENT_RUN_STARTED"
    STEP_STARTED = "AGENT_STEP_STARTED"
    STEP_FINISHED = "AGENT_STEP_FINISHED"
    STEP_FAILED = "AGENT_STEP_FAILED"
    USER_ACTION_REQUIRED = "USER_ACTION_REQUIRED"
    RUN_PAUSED = "AGENT_RUN_PAUSED"
    RUN_RESUMED = "AGENT_RUN_RESUMED"
    RUN_COMPLETED = "AGENT_RUN_COMPLETED"
    RUN_CANCELLED = "AGENT_RUN_CANCELLED"
    RUN_FAILED = "AGENT_FAILED"
    RUN_TIMED_OUT = "AGENT_TIMED_OUT"
    TOOL_REJECTED = "TOOL_REJECTED"
    TOOL_REPLANNED = "TOOL_REPLANNED"
